image: microsoft/dotnet
stages:
  - build
  - test
  - buildPrototypes
build:
  stage: build
  script:
    - 'dotnet build AnalogGameEngine.sln'
test:
  stage: test
  script:
    - 'dotnet test AnalogGameEngine.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="../OpenCover/"'
    - 'curl -s https://codecov.io/bash > codecov'
    - 'chmod +x codecov'
    - './codecov -f "OpenCover/coverage.opencover.xml" -t $CODECOV_TOKEN'
buildMauMau:
  stage: buildPrototypes
  script:
    - 'dotnet build MauMauPrototype/MauMauPrototype.csproj'
