image: microsoft/dotnet
stages:
  - build
  - test
  - code_quality
  - build_prototypes
build:
  stage: build
  script:
    - 'dotnet build AnalogGameEngine'
test:
  stage: test
  script:
    - 'dotnet test AnalogGameEngine.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
    # Upload to codecov
    - 'curl -s https://codecov.io/bash > codecov'
    - 'chmod +x codecov'
    - './codecov -f "AnalogGameEngine.Tests/coverage.opencover.xml" -t $CODECOV_TOKEN'
code_quality:
  stage: code_quality
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
buildMauMau:
  stage: build_prototypes
  script:
    - 'dotnet build MauMauPrototype'
