version: 1.0.{build}
before_build:
  - dotnet restore
  - choco install opencover.portable
  - choco install codecov
install:
  - git submodule update --init --recursive
build_script:
  - dotnet build
test_script:
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full C:\projects\CardGame-Engine\CardGameEngine.Tests\CardGameEngine.Tests.csproj" -filter:"+[CardGameEngine*]*" -output:".\my_app_coverage.xml" -oldstyle
after_test:
  - codecov -f .\my_app_coverage.xml
